name: tarot_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  morphable_shape: ^1.5.1
  easy_localization: ^3.0.0
  dimension: ^0.1.6
  audioplayers: ^0.19.0
  path_provider: ^2.0.1
  circle_list: ^1.0.4
  flutter_spinwheel: ^0.1.0
  simple_animations: ^3.1.1
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/characters/
    - assets/fonts/
    - assets/music/
    - assets/translations/

  fonts:
    - family: baskvill
      fonts:
        - asset: assets/fonts/BASKVILL.ttf
    - family: malgun
      fonts:
        - asset: assets/fonts/malgun.ttf
    - family: sherlock
      fonts:
        - asset: assets/fonts/Sherlock Vintage.ttf